site_name: linear-algebra
site_description: Python scripts for NUS MA1522 Linear Algebra for Computing
site_author: Yee Shin Teng
repo_url: https://github.com/YeeShin504/linear-algebra
repo_name: YeeShin504/linear-algebra

nav:
  - Home: index.md
  - API Reference: api/
  - Tutorial: Tutorials/Tutorial.md
  - Example Notebook: scrap.ipynb

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - tags
  - mkdocs-jupyter
  - gen-files:
      scripts:
        - docs/assets/python/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.sympy.org/latest/objects.inv
          options:
            docstring_style: google
            show_bases: true
            show_signature_annotations: true
            show_source: true
            find_stubs_package: true
            allow_inspection: false
          paths: [src]
  - autorefs:

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe
  # - assets/javascripts/hljs-init.js
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css
  # Or choose a different theme:
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css
