site_name: linear-algebra
site_description: Python scripts for NUS MA1522 Linear Algebra for Computing
site_author: Yee Shin Teng
repo_url: https://github.com/YeeShin504/linear-algebra
repo_name: YeeShin504/linear-algebra
watch: [mkdocs.yml, README.md, src, docs]
copyright: Copyright &copy; 2025 Yee Shin Teng

nav:
  - Home:
      - Overview: index.md
      - License: license.md
  - API Reference:
      - custom_types: api/custom_types.md
      - symbolic: api/symbolic.md
      - inherited methods: api/inherited.md
      - utils: api/utils.md
  - Tutorial:
      - Quickstart: Tutorials/Tutorial.md
      - Tutorial 1: Tutorials/Tut01.ipynb
      - Tutorial 2: Tutorials/Tut02.ipynb
      - Tutorial 3: Tutorials/Tut03.ipynb
      - Tutorial 4: Tutorials/Tut04.ipynb
      - Tutorial 5: Tutorials/Tut05.ipynb
      - Tutorial 6: Tutorials/Tut06.ipynb
      - Tutorial 7: Tutorials/Tut07.ipynb
      - Tutorial 8: Tutorials/Tut08.ipynb
      - Tutorial 9: Tutorials/Tut09.ipynb
      - Tutorial 10: Tutorials/Tut10.ipynb
      - Tutorial 11: Tutorials/Tut11.ipynb

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - autorefs:
      resolve_closest: true
  - search
  - tags
  - mkdocs-jupyter:
      jupyter_execute_notebooks: on
  - mkdocstrings:
      default_handler: python_xref
      handlers:
        python_xref:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.sympy.org/latest/objects.inv
            - https://ipython.readthedocs.io/en/stable/objects.inv
            - https://mpmath.org/doc/current/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            allow_inspection: false
            backlinks: true
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            docstring_style: google
            find_stubs_package: true
            heading_level: 2
            # inherited_members: false
            line_length: 88
            members_order: __all__
            merge_init_into_class: true
            # parameter_headings: true
            preload_modules:
              - sympy
            relative_crossrefs: true
            check_crossrefs_exclude:
              - "^sympy\\.(.*)"
            show_bases: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true

markdown_extensions:
  - admonition
  # - codehilite:
  #     guess_lang: false
  #     use_pygments: true
  #     css_class: codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: false
      line_spans: __span
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe
  # - assets/javascripts/hljs-init.js
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css
  # Or choose a different theme:
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css
