site_name: My Docs

nav:
  - Home: index.md
  - API Doccumentation: reference/
  - Tutorial: Tutorials/Tutorial.md
  - Example Notebook: scrap.ipynb

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

plugins:
  - search
  - mkdocs-jupyter
  - gen-files:
      scripts:
        - docs/assets/python/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - autorefs:

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  # - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe
