name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests on Multiple OS
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest ]   
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: |    
          uv python install ${{ matrix.python-version }}
          uv sync
          uv pip install -e . 

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install pytest
    #       pip install -r requirements.txt

      - name: Run tests
        run: |
          uv run --python ${{ matrix.python-version }} pytest tests/
    
      - name: Run docstring tests
        run: |
          uv run --python ${{ matrix.python-version }} pytest --doctest-modules 
